# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AssignmentExpedia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Toast', '~> 4.0.0'
  pod 'Kingfisher'

  # Pods for AssignmentExpedia

  target 'AssignmentExpediaTests' do
    inherit! :search_paths
    pod 'Toast', '~> 4.0.0'
    pod 'Kingfisher'
    # Pods for testing
  end

  target 'AssignmentExpediaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
